import { z } from "zod";

export const TeamSelector = z.object({
  team: z.string(),
});

export const teams = [
  { abbr: "ATL", name: "Atlanta Hawks" },
  { abbr: "BOS", name: "Boston Celtics" },
  { abbr: "BKN", name: "Brooklyn Nets" },
  { abbr: "CHA", name: "Charlotte Hornets" },
  { abbr: "CHI", name: "Chicago Bulls" },
  { abbr: "CLE", name: "Cleveland Cavaliers" },
  { abbr: "DAL", name: "Dallas Mavericks" },
  { abbr: "DEN", name: "Denver Nuggets" },
  { abbr: "DET", name: "Detroit Pistons" },
  { abbr: "GSW", name: "Golden State Warriors" },
  { abbr: "HOU", name: "Houston Rockets" },
  { abbr: "IND", name: "Indiana Pacers" },
  { abbr: "LAC", name: "Los Angeles Clippers" },
  { abbr: "LAL", name: "Los Angeles Lakers" },
  { abbr: "MEM", name: "Memphis Grizzlies" },
  { abbr: "MIA", name: "Miami Heat" },
  { abbr: "MIL", name: "Milwaukee Bucks" },
  { abbr: "MIN", name: "Minnesota Timberwolves" },
  { abbr: "NOP", name: "New Orleans Pelicans" },
  { abbr: "NYK", name: "New York Knicks" },
  { abbr: "OKC", name: "Oklahoma City Thunder" },
  { abbr: "ORL", name: "Orlando Magic" },
  { abbr: "PHI", name: "Philadelphia 76ers" },
  { abbr: "PHX", name: "Phoenix Suns" },
  { abbr: "POR", name: "Portland Trail Blazers" },
  { abbr: "SAC", name: "Sacramento Kings" },
  { abbr: "SAS", name: "San Antonio Spurs" },
  { abbr: "TOR", name: "Toronto Raptors" },
  { abbr: "UTA", name: "Utah Jazz" },
  { abbr: "WAS", name: "Washington Wizards" },
];

export const teamThemes = {
  all: "theme-all",
  ATL: "theme-ATL",
  BOS: "theme-BOS",
  BKN: "theme-BKN",
  CHA: "theme-CHA",
  CHI: "theme-CHI",
  CLE: "theme-CLE",
  DAL: "theme-DAL",
  DEN: "theme-DEN",
  DET: "theme-DET",
  GSW: "theme-GSW",
  HOU: "theme-HOU",
  IND: "theme-IND",
  LAC: "theme-LAC",
  LAL: "theme-LAL",
  MEM: "theme-MEM",
  MIA: "theme-MIA",
  MIL: "theme-MIL",
  MIN: "theme-MIN",
  NOP: "theme-NOP",
  NYK: "theme-NYK",
  OKC: "theme-OKC",
  ORL: "theme-ORL",
  PHI: "theme-PHI",
  PHX: "theme-PHX",
  POR: "theme-POR",
  SAC: "theme-SAC",
  SAS: "theme-SAS",
  TOR: "theme-TOR",
  UTA: "theme-UTA",
  WAS: "theme-WAS",
};
